<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="Dto\**" />
    <Compile Remove="Handlers\**" />
    <EmbeddedResource Remove="Dto\**" />
    <EmbeddedResource Remove="Handlers\**" />
    <None Remove="Dto\**" />
    <None Remove="Handlers\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Domain\Domain.csproj" />
    <ProjectReference Include="..\Files.Domain\Files.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

</Project>
