// <auto-generated />
using System;
using Chat.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chat.Infrastructure.Migrations
{
    [DbContext(typeof(WriteChatDbContext))]
    partial class WriteChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "ru_RU.UTF-8,ru_RU.UTF-8,icu,False")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gin");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chat.Domain.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long?>("TgMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("citext");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasFilter("\"TgMessageId\" IS NULL AND \"Direction\" = 0");

                    b.HasIndex("TgMessageId")
                        .IsUnique()
                        .HasFilter("\"TgMessageId\" IS NOT NULL");

                    b.HasIndex("SessionId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.ChatSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AdminChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Culture")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Page")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("citext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("TopicMessageId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("TopicMessageId");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.ChatMessageEntity", b =>
                {
                    b.OwnsOne("Domain.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ChatMessageEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<Guid?>("CreatedById")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ModifiedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<Guid?>("ModifiedById")
                                .HasColumnType("uuid");

                            b1.HasKey("ChatMessageEntityId");

                            b1.ToTable("ChatMessages");

                            b1.WithOwner()
                                .HasForeignKey("ChatMessageEntityId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("Chat.Domain.ChatSessionEntity", b =>
                {
                    b.OwnsOne("Domain.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ChatSessionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<Guid?>("CreatedById")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ModifiedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("NOW()");

                            b1.Property<Guid?>("ModifiedById")
                                .HasColumnType("uuid");

                            b1.HasKey("ChatSessionEntityId");

                            b1.ToTable("ChatSessions");

                            b1.WithOwner()
                                .HasForeignKey("ChatSessionEntityId");
                        });

                    b.Navigation("Audit");
                });
#pragma warning restore 612, 618
        }
    }
}
