<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\backend\shared\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
