<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\MessageBus\MessageBus.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localizer\SharedStrings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localizer\SharedStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedStrings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
